# Generated by Django 4.0.5 on 2022-06-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_category_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
